version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./log:/app/log
      - ./craap_results:/app/craap_results
      - ./craap_results_v2:/app/craap_results_v2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s