services:
  - type: web
    name: matrix-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true