# Render.com deployment configuration
# This file can be used to configure your Render service

# Service Configuration
name: matrix-of-truth-backend
type: web
env: docker
dockerfilePath: ./Dockerfile
dockerContext: ./

# Build Configuration
buildCommand: ""  # Docker handles the build

# Runtime Configuration
startCommand: "python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

# Environment Variables (set these in Render dashboard)
# PORT - will be set automatically by Render
# RENDER_SERVICE_NAME - will be set automatically by Render
# Add your custom environment variables:
# - FIREBASE_CONFIG
# - PUSHER_APP_ID
# - PUSHER_KEY
# - PUSHER_SECRET
# - PUSHER_CLUSTER
# - GROQ_API_KEY
# - SERPER_API_KEY
# - NEWSAPI_KEY
# - Any other API keys from your .env file

# Health Check
healthCheckPath: /health

# Auto-Deploy
autoDeploy: true
branch: main

# Scaling
numInstances: 1
plan: starter  # or higher as needed

# Disk
disk:
  name: matrix-backend-disk
  mountPath: /app/data
  sizeGB: 1

# Additional Notes:
# 1. Make sure to set all environment variables in Render dashboard
# 2. The Docker image will be built automatically
# 3. Health checks will use the /health endpoint
# 4. Logs will be available in Render dashboard